export const radicalDict: Record<string, string> = {
  "一": "Nhất (Một)",
  "丨": "Cổn (Nét sổ)",
  "丶": "Chủ (Nét chấm)",
  "丿": "Phiệt (Nét phẩy)",
  "乙": "Ất (Thiên can thứ hai)",
  "亅": "Quyết (Nét móc)",
  "二": "Nhị (Hai)",
  "亠": "Đầu (Phần đầu)",
  "人": "Nhân (Người)",
  "亻": "Nhân đứng (Người)",
  "儿": "Nhi (Trẻ con)",
  "入": "Nhập (Vào)",
  "八": "Bát (Tám)",
  "冂": "Quynh (Vùng biên giới)",
  "冖": "Mịch (Trùm lên)",
  "冫": "Băng (Nước đá)",
  "几": "Kỷ (Bàn nhỏ)",
  "凵": "Khảm (Há miệng)",
  "刀": "Đao (Dao)",
  "刂": "Đao (Dao)",
  "力": "Lực (Sức mạnh)",
  "勹": "Bao (Bao bọc)",
  "匕": "Chủy (Cái thìa)",
  "匚": "Phương (Tủ, hộp)",
  "匸": "Hệ (Che đậy)",
  "十": "Thập (Mười)",
  "卜": "Bốc (Xem bói)",
  "卩": "Tiết (Đốt tre)",
  "厂": "Hán (Sườn núi)",
  "厶": "Khư (Riêng tư)",
  "又": "Hựu (Lại, tay phải)",
  "口": "Khẩu (Miệng)",
  "囗": "Vi (Bao quanh)",
  "土": "Thổ (Đất)",
  "士": "Sĩ (Kẻ sĩ)",
  "夂": "Truy (Đi theo)",
  "夕": "Tịch (Buổi tối)",
  "大": "Đại (To lớn)",
  "女": "Nữ (Phụ nữ)",
  "子": "Tử (Con cái)",
  "宀": "Miên (Mái nhà)",
  "寸": "Thốn (Đơn vị đo)",
  "小": "Tiểu (Nhỏ bé)",
  "尢": "Uông (Què, yếu)",
  "尸": "Thi (Xác chết)",
  "屮": "Triệt (Cỏ mới mọc)",
  "山": "Sơn (Núi)",
  "巛": "Xuyên (Sông)",
  "川": "Xuyên (Sông)",
  "工": "Công (Thợ, việc)",
  "己": "Kỷ (Bản thân)",
  "巾": "Cân (Cái khăn)",
  "干": "Can (Cái khiên, can dự)",
  "幺": "Yêu (Nhỏ bé)",
  "广": "Nghiễm (Mái nhà rộng)",
  "廴": "Dẫn (Bước dài)",
  "廾": "Củng (Chắp tay)",
  "弋": "Dực (Cái cọc)",
  "弓": "Cung (Cây cung)",
  "彐": "Kệ (Đầu con nhím)",
  "彡": "Sam (Lông tóc)",
  "彳": "Sách (Bước ngắn)",
  "心": "Tâm (Trái tim)",
  "忄": "Tâm đứng",
  "戈": "Qua (Cái qua - binh khí)",
  "戶": "Hộ (Cửa 1 cánh)",
  "手": "Thủ (Tay)",
  "扌": "Thủ (Tay)",
  "支": "Chi (Cành nhánh)",
  "攴": "Phộc (Đánh nhẹ)",
  "攵": "Phộc (Đánh nhẹ)",
  "文": "Văn (Văn chương)",
  "斗": "Đẩu (Cái đấu)",
  "斤": "Cân (Cái búa, cân)",
  "方": "Phương (Vuông)",
  "无": "Vô (Không có)",
  "日": "Nhật (Mặt trời)",
  "曰": "Viết (Nói)",
  "月": "Nguyệt (Mặt trăng)",
  "木": "Mộc (Cây, gỗ)",
  "欠": "Khiếm (Thiếu)",
  "止": "Chỉ (Dừng lại)",
  "歹": "Đãi (Xấu xa)",
  "殳": "Thù (Binh khí dài)",
  "毋": "Vô (Chớ, đừng)",
  "比": "Tỷ (So sánh)",
  "毛": "Mao (Lông)",
  "氏": "Thị (Họ)",
  "气": "Khí (Hơi, khí)",
  "水": "Thủy (Nước)",
  "氵": "Thủy (Nước)",
  "火": "Hỏa (Lửa)",
  "灬": "Hỏa (Lửa)",
  "爪": "Trảo (Móng vuốt)",
  "父": "Phụ (Cha)",
  "爻": "Hào (Hào trong bát quái)",
  "爿": "Tường (Tấm ván)",
  "片": "Phiến (Mảnh, tấm)",
  "牙": "Nha (Răng)",
  "牛": "Ngưu (Trâu bò)",
  "犬": "Khuyển (Chó)",
  "犭": "Khuyển (Chó)",
  "玄": "Huyền (Màu đen)",
  "玉": "Ngọc (Đá quý)",
  "瓜": "Qua (Dưa)",
  "瓦": "Ngõa (Ngói)",
  "甘": "Cam (Ngọt)",
  "生": "Sinh (Sinh đẻ)",
  "用": "Dụng (Dùng)",
  "田": "Điền (Ruộng)",
  "疋": "Thất (Đơn vị vải)",
  "疒": "Nạch (Bệnh tật)",
  "癶": "Bát (Gạt chân)",
  "白": "Bạch (Màu trắng)",
  "皮": "Bì (Da)",
  "皿": "Mãnh (Đồ sành sứ)",
  "目": "Mục (Mắt)",
  "矛": "Mâu (Giáo mác)",
  "矢": "Thỉ (Mũi tên)",
  "石": "Thạch (Đá)",
  "示": "Thị (Chỉ bảo)",
  "礻": "Thị (Chỉ bảo)",
  "禸": "Nhựu (Vết chân)",
  "禾": "Hòa (Lúa)",
  "穴": "Huyệt (Hang lỗ)",
  "立": "Lập (Đứng)",
  "竹": "Trúc (Tre trúc)",
  "米": "Mễ (Gạo)",
  "糸": "Mịch (Sợi tơ nhỏ)",
  "纟": "Mịch (Sợi tơ)",
  "缶": "Phẫu (Đồ sành)",
  "网": "Võng (Lưới)",
  "羊": "Dương (Dê)",
  "羽": "Vũ (Lông chim)",
  "老": "Lão (Già)",
  "而": "Nhi (Và, mà)",
  "耒": "Lỗi (Cày bừa)",
  "耳": "Nhĩ (Tai)",
  "聿": "Duật (Cây bút)",
  "肉": "Nhục (Thịt)",
  "臣": "Thần (Quan)",
  "自": "Tự (Bản thân)",
  "至": "Chí (Đến)",
  "臼": "Cữu (Cối giã)",
  "舌": "Thiệt (Lưỡi)",
  "舛": "Suyễn (Trái ngược)",
  "舟": "Chu (Thuyền)",
  "艮": "Cấn (Quẻ Cấn, dừng)",
  "色": "Sắc (Màu sắc)",
  "艸": "Thảo (Cỏ)",
  "艹": "Thảo (Cỏ)",
  "虍": "Hô (Vằn hổ)",
  "虫": "Trùng (Côn trùng)",
  "血": "Huyết (Máu)",
  "行": "Hành (Đi lại)",
  "衣": "Y (Áo)",
  "衤": "Y (Áo)",
  "襾": "Á (Che đậy)",
  "见": "Kiến (Nhìn thấy)",
  "角": "Giác (Cái sừng)",
  "言": "Ngôn (Nói)",
  "讠": "Ngôn (Nói)",
  "谷": "Cốc (Khe núi)",
  "豆": "Đậu (Hạt đậu)",
  "豕": "Thỉ (Heo, lợn)",
  "豸": "Trãi (Loài sâu không chân)",
  "贝": "Bối (Bảo bối)",
  "赤": "Xích (Màu đỏ)",
  "走": "Tẩu (Chạy)",
  "足": "Túc (Chân)",
  "身": "Thân (Cơ thể)",
  "车": "Xa (Xe)",
  "辛": "Tân (Cay, vất vả)",
  "辰": "Thần (Sáng sớm)",
  "辵": "Sước (Đi dạo)",
  "辶": "Sước (Đi dạo)",
  "邑": "Ấp (Vùng đất)",
  "阝": "Ấp/Phụ (Đất/Gò đất)",
  "酉": "Dậu (Rượu)",
  "采": "Thái (Hái lượm)",
  "里": "Lý (Dặm)",
  "金": "Kim (Kim loại)",
  "钅": "Kim (Kim loại)",
  "长": "Trường (Dài)",
  "门": "Môn (Cửa)",
  "阜": "Phụ (Gò đất)",
  "隶": "Đãi (Đuổi bắt)",
  "隹": "Chuy (Chim đuôi ngắn)",
  "雨": "Vũ (Mưa)",
  "青": "Thanh (Màu xanh)",
  "非": "Phi (Sai, không)",
  "面": "Diện (Mặt)",
  "革": "Cách (Da thú)",
  "韦": "Vi (Da đã thuộc)",
  "韭": "Cửu (Rau hẹ)",
  "音": "Âm (Âm thanh)",
  "页": "Hiệt (Trang giấy, cái đầu)",
  "风": "Phong (Gió)",
  "飞": "Phi (Bay)",
  "食": "Thực (Ăn)",
  "饣": "Thực (Ăn)",
  "首": "Thủ (Cái đầu)",
  "香": "Hương (Mùi thơm)",
  "马": "Mã (Con ngựa)",
  "骨": "Cốt (Xương)",
  "高": "Cao (Cao lớn)",
  "髟": "Bưu (Tóc dài)",
  "鬥": "Đấu (Đánh nhau)",
  "鬯": "Xưởng (Rượu ủ nếp)",
  "鬲": "Cách (Nồi, đỉnh)",
  "鬼": "Quỷ (Ma quỷ)",
  "鱼": "Ngư (Cá)",
  "鸟": "Điểu (Chim)",
  "卤": "Lỗ (Đất mặn)",
  "鹿": "Lộc (Con hươu)",
  "麦": "Mạch (Lúa mạch)",
  "麻": "Ma (Cây gai)",
  "黄": "Hoàng (Màu vàng)",
  "黍": "Thử (Lúa nếp)",
  "黑": "Hắc (Màu đen)",
  "黹": "Chỉ (Khâu vá)",
  "黾": "Mãnh (Con ếch)",
  "鼎": "Đỉnh (Cái đỉnh)",
  "鼓": "Cổ (Cái trống)",
  "鼠": "Thử (Con chuột)",
  "鼻": "Tị (Mũi)",
  "齐": "Tề (Bằng phẳng)",
  "齿": "Xỉ (Răng)",
  "龙": "Long (Rồng)",
  "龟": "Quy (Rùa)",
  "龠": "Dược (Ống sáo)"
};
